### ISSUE TITLE
bad groovy colors in dark theme

### ISSUE THREAD

**Issue by vbasem** [mallowigi/material-theme-jetbrains#12]
Groovy doesn't seem to be usable in dark theme. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/554690/25134634/6ad42d2c-2450-11e7-81d3-cb36631b4ff6.png)

control elements and unresolved variables have bad contrast against the dark background.

**Comment by mallowigi** [comment]
Are you sure you have the latest version of the plugin? Also if you made some changes to the builtin color schemes - any change, not necessarily related to Groovy - you won't get the plugin updates. Make sure you do "restore defaults".

**Comment by vbasem** [comment]
It seems I had some left overs from the original material theme project with that problem.  After deleting my config dir everything seems fine. Thank you!
