### ISSUE TITLE
[3.3.4] Tiny new buttons

### ISSUE THREAD

**Issue by vemilyus** [mallowigi/material-theme-jetbrains#13]
Heya, the new button design looks nice and all, but on a scaled display the button labels look very small compared to everything else.

<img width="762" alt="material-scaling" src="https://cloud.githubusercontent.com/assets/7115009/25304125/0c43bee4-2761-11e7-9357-a20e413ddfe5.PNG">
This was obviously taken on Windows 10, with a display scaling factor of 150%

**Comment by mallowigi** [comment]
I can't test on such displays, but I can imagine where the problem is located. Do you have an email that I can contact you so I can send you the fix to test locally before I release a version?

**Comment by vemilyus** [comment]
Just updated my profile with my email address. Go nuts ;)
