### ISSUE TITLE
New buttons hard to distinguish

### ISSUE THREAD

**Issue by mikemand** [mallowigi/material-theme-jetbrains#16]
Could you add a border or some other contrast to help distinguish buttons from the rest of the interface? With them flat like they are, it's hard to tell that they are something I can click on; they look like regular text.

**Comment by mallowigi** [comment]
I'm experimenting on adding some contrast in them, but for the moment you can still disable the new looks in the Settings

**Comment by mallowigi** [comment]
Should be fixed in the lastes release

**Comment by mikemand** [comment]
That works. Thanks!

**Comment by nazrhyn** [comment]
Thanks, again :+1:!
