### ISSUE TITLE
Ruby color scheme partially using Darcula colors

### ISSUE THREAD

**Issue by Kendos-Kenlen** [mallowigi/material-theme-jetbrains#18]
Hi,

Some elements such as Class/Global variables and local variables aren't themed with material colors in the bundled color scheme and use the default colors. It looks a bit strange :

![screenshot_20170428_113423](https://cloud.githubusercontent.com/assets/2579741/25523357/a5351ed2-2c06-11e7-8123-c2424c49b4aa.png)

Operator, "require", "public/private/protected" (and maybe some other Ruby or Rails special calls), comment, heredoc, strings, local variables and class/global variables are not stylized (non exhaustive list).

**Comment by mallowigi** [comment]
Should be fixed in the latest release

**Comment by mallowigi** [comment]
Can we close this issue?

**Comment by Kendos-Kenlen** [comment]
yeap it's better now :)
