### ISSUE TITLE
Remove warning message for Darker theme

### ISSUE THREAD

**Issue by josephtaylor** [mallowigi/material-theme-jetbrains#3]
Is the Darker theme really _that_ much of a work in progress that it requires a warning pop-up when you switch to it?
I feel like it's solid enough to drop the warning. Is that possible?

I've been using it for a few weeks now in WebStorm, Intellij, and DataGrip with no issues.

**Comment by mallowigi** [comment]
Yes, there are still issues that are yet to be fixed. Besides, I'm using the settings of ChrisRM which might not be up to date with esquinocio (the sublime theme creator)

**Comment by mallowigi** [comment]
I've updated the plugin so this issue is not relevant anymore.
