### ISSUE TITLE
Breakpoint highlight is off for palenight theme

### ISSUE THREAD

**Issue by anidotnet** [mallowigi/material-theme-jetbrains#6]
When the palenight theme is on and the editor hits a breakpoint, the normal line highlight is not being shown. It is very hard to recognise which line is currently at pause. Please fix it. Otherwise this particular theme is off the hook!

IntelliJ Idea : 2017.1
OS: Ubuntu 16.04.02

**Comment by mallowigi** [comment]
Please update the plugin with the new version, it should contain your request.

**Comment by anidotnet** [comment]
Please reopen the issue, as it seems it is not resolved. Please see the screenshots below with the latest version of the plugin 

![image](https://cloud.githubusercontent.com/assets/696662/24838888/69435642-1d6e-11e7-8250-6687130e811a.png)

But when I have set the color & font of the editor to Darcula, the highlighting is coming up as below. 

![image](https://cloud.githubusercontent.com/assets/696662/24838917/cc617d94-1d6e-11e7-8b7c-00cba5cc5ab8.png)

The highlighting is only not coming when I select editor's color & font as palenight.

![image](https://cloud.githubusercontent.com/assets/696662/24838932/17e6fcbc-1d6f-11e7-80d4-382c4cb99327.png)

**Comment by mallowigi** [comment]
I am not able to reproduce this. Maybe because I'm not on Linux? 

http://prntscr.com/eue2kr

I'll try to borrow a Linux machine at work one day and see if this reproduces.

**Comment by anidotnet** [comment]
OS might be the reason. I am currently on Ubuntu 16.04.02 with budgie desktop. Let me know if you need anymore details.

**Comment by mallowigi** [comment]
I have just checked out and it still gives me the correct color in Linux... Maybe you edited the color scheme? In any case please have a look at Settings > Editor > Colors and Fonts > Debugger, there you can set the value you want to.

Also FYI by the time you edit one of the themes it creates a copy so maybe you didn't get the new theme colors? Not sure though, sorry.

**Comment by anidotnet** [comment]
Thanks a lot, I got it working, after resetting the theme colors to default. I did change the font details of the theme, but no colors, but somehow updating the theme plugin did not help last time. When I reset it, it started reflecting the change. Thanks again for your time and quick response.
