### ISSUE TITLE
Can you make excluded folders less noticeable 

### ISSUE THREAD

**Issue by WiseBird** [mallowigi/material-theme-jetbrains#8]
At the moment they are highlighted in such a way as if they are main focus:
![2](https://cloud.githubusercontent.com/assets/1745378/24721771/682ef1cc-1a52-11e7-9b34-b38f9fcb03bd.png)

Maybe better to gray them out or something.

**Comment by mallowigi** [comment]
Please update the plugin and tell me if this is what you implied

**Comment by WiseBird** [comment]
I updated to version 0.3.3 But don't see any difference. Excluded directories still have highlighted background.

**Comment by mallowigi** [comment]
Ah i understand, but this has nothing to do with the plugin, instead you have to go to Settings > Appearance and behavior > File Colors. There you will see that excluded files have that tinted yellow color, and you can edit or remove it if you need to.

--
Elior

**Comment by WiseBird** [comment]
Big thanks! Sorry for bothering you.
