### ISSUE TITLE
Tabs not using theme colors

### ISSUE THREAD

**Issue by RamyTalal** [mallowigi/material-theme-jetbrains#9]
Is it normal that active tabs aren't styled to match the theme?
![capture](https://cloud.githubusercontent.com/assets/188874/24836891/3ef713e2-1d28-11e7-8b05-715342f71af2.PNG)

**Comment by mallowigi** [comment]
This looks like something you put on an excluded folder. You have to set it yourself in Settings > Appearance and Behavior > File Colors and uncheck the "Use in Editor Tabs"

**Comment by RamyTalal** [comment]
Thanks!
